name: MoonSalary
version: '${project.version}'
main: com.ney.moonsalary.MoonSalary
api-version: 1.16
author: Ney
description: Salary for donation groups with AFK protection
softdepend: [Vault, PlaceholderAPI]

commands:
  salary:
    description: Main command of the MoonSalary plugin
    usage: /<command> [info|reload|list] [player]
    aliases: [msalary, zp]

permissions:
  moonsalary.admin.reload:
    description: Allows to reload the plugin configuration
    default: op
  moonsalary.admin.list:
    description: Allows to view all configured salary groups
    default: op
  moonsalary.bypass.afk:
    description: Allows to receive a salary while being AFK
    default: false
